### ISSUE TITLE
Blank anomaly result page when initialization failed

### ISSUE THREAD

**Issue by ylwu-amzn** [opendistro-for-elasticsearch/anomaly-detection-kibana-plugin#162]
Re-initialization failed, AD result page shows nothing.

![Screen Shot 2020-05-19 at 11 53 42 AM](https://user-images.githubusercontent.com/49084640/82366764-94127280-99c7-11ea-8e27-f21454f269d8.png)

Check AD result:
```
{
    "detector_id" : "yNpUXXEBPdSnBWCFN-zN",
    "data_start_time" : 1589910474476,
    "data_end_time" : 1589910534476,
    "feature_data" : [ ],
    "execution_start_time" : 1589910534476,
    "execution_end_time" : 1589910534505,
    "error" : "Stopped detector as job failed consecutively for more than 3 times: We might have bugs."
  }

{
    "detector_id" : "yNpUXXEBPdSnBWCFN-zN",
    "data_start_time" : 1589910414476,
    "data_end_time" : 1589910474476,
    "feature_data" : [ ],
    "execution_start_time" : 1589910474476,
    "execution_end_time" : 1589910474505,
    "error" : "We might have bugs."
  }

{
    "detector_id" : "yNpUXXEBPdSnBWCFN-zN",
    "data_start_time" : 1589910354476,
    "data_end_time" : 1589910414476,
    "feature_data" : [ ],
    "execution_start_time" : 1589910414476,
    "execution_end_time" : 1589910414536,
    "error" : "We might have bugs."
  }

{
    "detector_id" : "yNpUXXEBPdSnBWCFN-zN",
    "data_start_time" : 1589910294476,
    "data_end_time" : 1589910354476,
    "feature_data" : [ ],
    "execution_start_time" : 1589910354476,
    "execution_end_time" : 1589910354514,
    "error" : "We might have bugs."
  }
```

**Comment by yizheliu-amazon** [comment]
"We might have bugs" is corresponding to `Unexpected failure`, we can change this [line](https://github.com/opendistro-for-elasticsearch/anomaly-detection-kibana-plugin/blob/master/public/pages/DetectorResults/containers/DetectorStateDetails.tsx#L58) to
```
    case DETECTOR_STATE.INIT_FAILURE:
    case DETECTOR_STATE.UNEXPECTED_FAILURE:
      const failureDetail = getInitFailureMessageAndActionItem(
        detector.initializationError
      );
...
```

**Comment by yizheliu-amazon** [comment]
Backend error stack trace:
```
[2020-05-19T17:27:53,722][ERROR][c.a.o.a.t.AnomalyResultTransportAction] [105773eab7d75468e6587eb835f66c75] Received an error from node FoAzrJP0QcC3q_s0z7rYtg while fetching anomaly grade for yNpUXXEBPdSnBWCFN-zN
org.elasticsearch.transport.RemoteTransportException: [8f49a9616d531ad45e3283fdf1561d21][10.212.17.141:9300][cluster:admin/ad/rcf/result]
Caused by: java.lang.IllegalArgumentException: point.length must equal 16
        at com.amazon.randomcutforest.CommonUtils.checkArgument(CommonUtils.java:40) ~[?:?]
        at com.amazon.randomcutforest.RandomCutForest.traverseForest(RandomCutForest.java:314) ~[?:?]
        at com.amazon.randomcutforest.RandomCutForest.getAnomalyScore(RandomCutForest.java:455) ~[?:?]
        at com.amazon.opendistroforelasticsearch.ad.ml.ModelManager.getRcfResult(ModelManager.java:383) ~[?:?]
        at com.amazon.opendistroforelasticsearch.ad.ml.ModelManager.getRcfResult(ModelManager.java:370) ~[?:?]
        at com.amazon.opendistroforelasticsearch.ad.transport.RCFResultTransportAction.doExecute(RCFResultTransportAction.java:61) ~[?:?]
        at com.amazon.opendistroforelasticsearch.ad.transport.RCFResultTransportAction.doExecute(RCFResultTransportAction.java:32) ~[?:?]
        at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:154) ~[elasticsearch-7.4.2.jar:7.4.2]
        at com.amazon.opendistro.elasticsearch.performanceanalyzer.action.PerformanceAnalyzerActionFilter.apply(PerformanceAnalyzerActionFilter.java:77) ~[?:?]
        at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:152) ~[elasticsearch-7.4.2.jar:7.4.2]
        at com.amazon.opendistroforelasticsearch.security.filter.OpenDistroSecurityFilter.apply0(OpenDistroSecurityFilter.java:218) ~[?:?]
        at com.amazon.opendistroforelasticsearch.security.filter.OpenDistroSecurityFilter.apply(OpenDistroSecurityFilter.java:119) ~[?:?]
        at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:152) ~[elasticsearch-7.4.2.jar:7.4.2]
        at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:130) ~[elasticsearch-7.4.2.jar:7.4.2]
        at org.elasticsearch.action.support.HandledTransportAction$TransportHandler.messageReceived(HandledTransportAction.java:64) ~[elasticsearch-7.4.2.jar:7.4.2]
        at org.elasticsearch.action.support.HandledTransportAction$TransportHandler.messageReceived(HandledTransportAction.java:60) ~[elasticsearch-7.4.2.jar:7.4.2]
        at com.amazon.opendistroforelasticsearch.security.ssl.transport.OpenDistroSecuritySSLRequestHandler.messageReceivedDecorate(OpenDistroSecuritySSLRequestHandler.java:182) ~[?:?]
        at com.amazon.opendistroforelasticsearch.security.transport.OpenDistroSecurityRequestHandler.messageReceivedDecorate(OpenDistroSecurityRequestHandler.java:285) ~[?:?]
        at com.amazon.opendistroforelasticsearch.security.ssl.transport.OpenDistroSecuritySSLRequestHandler.messageReceived(OpenDistroSecuritySSLRequestHandler.java:142) ~[?:?]
        at com.amazon.opendistroforelasticsearch.security.OpenDistroSecurityPlugin$7$1.messageReceived(OpenDistroSecurityPlugin.java:655) ~[?:?]
        at com.amazonaws.elasticsearch.iam.IamTransportRequestHandler.messageReceived(IamTransportRequestHandler.java:50) ~[?:?]
        at com.amazon.opendistro.elasticsearch.performanceanalyzer.transport.PerformanceAnalyzerTransportRequestHandler.messageReceived(PerformanceAnalyzerTransportRequestHandler.java:48) ~[?:?]
        at com.amazonaws.elasticsearch.ccs.CrossClusterRequestInterceptor$CrossClusterRequestHandler.messageReceived(CrossClusterRequestInterceptor.java:133) ~[?:?]
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:63) ~[elasticsearch-7.4.2.jar:7.4.2]
        at org.elasticsearch.transport.InboundHandler$RequestHandler.doRun(InboundHandler.java:264) ~[elasticsearch-7.4.2.jar:7.4.2]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:36) ~[elasticsearch-7.4.2.jar:7.4.2]
        at org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService.execute(EsExecutors.java:236) ~[elasticsearch-7.4.2.jar:7.4.2]
        at org.elasticsearch.transport.InboundHandler.handleRequest(InboundHandler.java:185) [elasticsearch-7.4.2.jar:7.4.2]
        at org.elasticsearch.transport.InboundHandler.messageReceived(InboundHandler.java:118) [elasticsearch-7.4.2.jar:7.4.2]
        at org.elasticsearch.transport.InboundHandler.inboundMessage(InboundHandler.java:102) [elasticsearch-7.4.2.jar:7.4.2]
        at org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:663) [elasticsearch-7.4.2.jar:7.4.2]
       at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:62) [transport-netty4-client-7.4.2.jar:7.4.2]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-transport-4.1.38.Final.jar:4.1.38.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-transport-4.1.38.Final.jar:4.1.38.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [netty-transport-4.1.38.Final.jar:4.1.38.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:328) [netty-codec-4.1.38.Final.jar:4.1.38.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:302) [netty-codec-4.1.38.Final.jar:4.1.38.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-transport-4.1.38.Final.jar:4.1.38.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-transport-4.1.38.Final.jar:4.1.38.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [netty-transport-4.1.38.Final.jar:4.1.38.Final]
        at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:241) [netty-handler-4.1.38.Final.jar:4.1.38.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-transport-4.1.38.Final.jar:4.1.38.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-transport-4.1.38.Final.jar:4.1.38.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [netty-transport-4.1.38.Final.jar:4.1.38.Final]
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1475) [netty-handler-4.1.38.Final.jar:4.1.38.Final]
        at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1224) [netty-handler-4.1.38.Final.jar:4.1.38.Final]
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1271) [netty-handler-4.1.38.Final.jar:4.1.38.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:505) [netty-codec-4.1.38.Final.jar:4.1.38.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:444) [netty-codec-4.1.38.Final.jar:4.1.38.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:283) [netty-codec-4.1.38.Final.jar:4.1.38.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-transport-4.1.38.Final.jar:4.1.38.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-transport-4.1.38.Final.jar:4.1.38.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [netty-transport-4.1.38.Final.jar:4.1.38.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1421) [netty-transport-4.1.38.Final.jar:4.1.38.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-transport-4.1.38.Final.jar:4.1.38.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-transport-4.1.38.Final.jar:4.1.38.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930) [netty-transport-4.1.38.Final.jar:4.1.38.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-transport-4.1.38.Final.jar:4.1.38.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:697) [netty-transport-4.1.38.Final.jar:4.1.38.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:597) [netty-transport-4.1.38.Final.jar:4.1.38.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:551) [netty-transport-4.1.38.Final.jar:4.1.38.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:511) [netty-transport-4.1.38.Final.jar:4.1.38.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918) [netty-common-4.1.38.Final.jar:4.1.38.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.38.Final.jar:4.1.38.Final]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by yizheliu-amazon** [comment]
After checking with Yaliang, how he triggered this is: when detector is running, disable AD plugin, and then re-enable AD, then update config of the detector to delete 1 feature, aka reduce 2 features to 1 feature, and start it again. 

The root cause is: disabling AD plugin only stops running AD job, but not clear models. This makes model still exists in `checkpoint` index. And the model saved in `checkpoint` expects 16 length feature data points. After reducing 1 feature, and re-enabling, when shingle is ready, model is loaded from `checkpoint` index, instead of training. In such case, the above error comes up.

**Comment by ylwu-amzn** [comment]
The fix needs to change AD ES plugin. Created a new issue  https://github.com/opendistro-for-elasticsearch/anomaly-detection/issues/132
