### ISSUE TITLE
Kibana 7.7.0 - babel-polyfill Error

### ISSUE THREAD

**Issue by chaleyeah** [opendistro-for-elasticsearch/anomaly-detection-kibana-plugin#198]
I'm running an Elastic Stack install using the X-pack Basic plugins.  My Kibana install is running Ubuntu 18.04 with JRE 11.  To be clear this is the Elastic.co X-Pack Basic version.   
When I attempt to load this plugin I'm getting the following error.  As this is an in-use kibana interface I have to remove the plugin and restart the services so my users don't get antsy.   
Please let me know if I need to provide any further info. 

Here is the specific lines from my /var/log/syslog output.  

`{"type":"log","@timestamp":"2020-06-04T18:12:31Z","tags":["fatal","root"],"pid":35159,"message":"Error: only one instance of babel-polyfill is allowed
at Object.<anonymous> (/usr/share/kibana/plugins/wazuh/node_modules/babel-polyfill/lib/index.js:10:9)
at Module._compile (internal/modules/cjs/loader.js:778:30)
at Module._compile (/usr/share/kibana/node_modules/pirates/lib/index.js:99:24)
at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
at Object.newLoader [as .js] (/usr/share/kibana/node_modules/pirates/lib/index.js:104:7)
at Module.load (internal/modules/cjs/loader.js:653:32)
at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
at Function.Module._load (internal/modules/cjs/loader.js:585:3)
at Module.require (internal/modules/cjs/loader.js:692:17)
at Module.Hook._require.Module.require (/usr/share/kibana/node_modules/require-in-the-middle/index.js:70:39)
at require (internal/modules/cjs/helpers.js:25:18)
at Object.<anonymous> (/usr/share/kibana/plugins/wazuh/node_modules/simple-tail/dist/index.js:7:1)
at Module._compile (internal/modules/cjs/loader.js:778:30)
at Module._compile (/usr/share/kibana/node_modules/pirates/lib/index.js:99:24)
at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
at Object.newLoader [as .js] (/usr/share/kibana/node_modules/pirates/lib/index.js:104:7)"}`

`FATAL  Error: only one instance of babel-polyfill is allowed`

**Comment by yizheliu-amazon** [comment]
Hi @chaleyeah,

Thanks for opening the issue.

I tried to reproduce your error with following steps, but not able to see the issue:
1. Download Linux binary of [ES-7.7.0](https://www.elastic.co/downloads/past-releases/elasticsearch-7-7-0) and [Kibana-7.7.0](https://www.elastic.co/downloads/past-releases/kibana-7-7-0)
1. Build artifact of [job-scheduler](https://github.com/opendistro-for-elasticsearch/job-scheduler/tree/v1.8.0.0) and [ad-es](https://github.com/opendistro-for-elasticsearch/anomaly-detection/tree/v1.8.0.0), and install both `job-scheduler`(must be installed first) and `ad-es` plugin to ES via `bin/elasticsearch-plugin install file://path/to/*1.8.0.0.zip`
1. Start ES via `bin/elasticsearch`
1. Build artifact of [ad-kibana-plugin](https://github.com/opendistro-for-elasticsearch/anomaly-detection-kibana-plugin/tree/v1.8.0.0), install it to kibana via `bin/kibana-plugin install file://path/to/opendistro-anomaly-detection-kibana-1.8.0.0.zip`
1. Start kibana via `bin/kibana`

Can you let me know how you install the AD ES/Kibana plugin?

**Comment by HagunKim** [comment]
I think it occurs because of wazuh plugin dependency.
According to this link, the problem seems to have been resolved.
[https://github.com/wazuh/wazuh-kibana-app/pull/2250](https://github.com/wazuh/wazuh-kibana-app/pull/2250)

**Comment by chaleyeah** [comment]
My apologies for the late replies.  I do have the Wazuh plugin installed.  I will test again today and let you know if there are still issues.

**Comment by chaleyeah** [comment]
@HagunKim was absolutely correct.  It was an issue with the Wazuh-Plugin.  Thanks for the tip, I'm all set.
